name: Deploy to itch.io

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Build
        run: |
          yarn --frozen-lockfile
          yarn build
      - name: Install butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Push to itch.io
        run: ./butler push dist aggressivepixels/chipster:web
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
